# configs/config.yaml

server:
  port: 8080
  # debug: true

cache:
  driver: redis
  host: localhost
  port: 6379

database:
  driver: postgres
  host: localhost
  port: 5432
  user: admin
  password: postgres-password
  dbname: bookstore
  sslmode: disable

# log:
#   level: debug
